//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Vishnu_Table1
    {
        public int SID { get; set; }
        public string SNAME { get; set; }
        public Nullable<int> MARKS { get; set; }
    }
}
